# Generated by Django 5.2.17 on 2026-10-01 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_diaryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
