# Generated by Django 5.2.17 on 2026-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carb_goal',
            field=models.FloatField(default=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fat_goal',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='protein_goal',
            field=models.FloatField(default=150),
        ),
    ]
