# Generated by Django 5.2.17 on 2026-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_food_is_custom_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
